### ISSUE TITLE
Unsuccessful stat on filename containing newline

### ISSUE THREAD

**Issue by edbmnt** [ovido/check_rhev3#36]
Example:

    $ sudo -u nagios ./plugin-dir/check_rhev3.pl -H my-very-long-rhev-manager-hostname -f /etc/check_rhev/check_rhev3.cfg -D foobar
    Unsuccessful stat on filename containing newline at ./plugin-dir/check_rhev3.pl line 1678.
    RHEV UNKNOWN: Datacenters foobar not found.
    $ 

It appears to be related to the way cookie filename is built. It may include newline when hostname combined with username@domain is too long.

    $ echo my-very-long-rhev-manager-hostname-myusername@my.domaine.com | base64
    bXktdmVyeS1sb25nLXJoZXYtbWFuYWdlci1ob3N0bmFtZS1teXVzZXJuYW1lQG15LmRvbWFpbmUu
    Y29tCg==
    $ 

Regards,
Eric

**Comment by scrat14** [comment]
Thanks a lot for reporting this bug and the fix!
