### ISSUE TITLE
tmp file not found in rhev3 1.3?

### ISSUE THREAD

**Issue by vAndrewJ** [ovido/check_rhev3#38]
Upgraded from 1.2 to 1.3 and now I get : 

>cat: /var/tmp/YXVzMDJnbW92aXJ0MDEuY29ycC52b2x1c2lvbi5jb20tc3ZjX25hZ2lvc0Bjb3JwLnZvbHVzaW9u: No such file or directory

**Comment by k0ste** [comment]
https://github.com/ovido/check_rhev3/releases/check_rhev3-1.4

**Comment by scrat14** [comment]
vAndrewJ, did you also try version 1.4 if the same error occurs?
Can you send me the debug output of the plugin with option -vvv via email to rkoch@rk-it.at? Thanks.

**Comment by vAndrewJ** [comment]
ok, 1.4 on the same system still results in the tmp error. Did you get the debug I sent?

**Comment by scrat14** [comment]
According to your debug output it could be this bug: #36 
Can you try this fix and let me know if it solved your issue: https://github.com/ovido/check_rhev3/commit/e538b7ab650e78e4965987581afed5037676b45a

**Comment by vAndrewJ** [comment]
That did it! Thanks!

**Comment by scrat14** [comment]
Thanks for the feedback - I'll close the issue as it's a duplicate to #36 
This bug will be officially fixed in 1.5.
