### ISSUE TITLE
check_rhev  not providing results after upgrade to  RHEVM 3.6 

### ISSUE THREAD

**Issue by rishisingh1210** [ovido/check_rhev3#43]
Hi Team,
 
 
We recently upgraded rhevm machine from  RHEVM3.2  to RHEVM3.6
 
After the upgrade  check_rhevm3 plugin is not able to get the data for host for most of the services as below
 
[root@mon01 libexec]# ./check_rhev3.pl -H XXXXXX -a nagios@internal:XXXXXX  -R hyp-app-03 -l memory
RHEV UNKNOWN: memory unknown - Performance data not found!
[root@mon01 libexec]# ./check_rhev3.pl -H XXXXXX -a nagios@internal:XXXXXX  -R hyp-app-03 -l cpu
RHEV UNKNOWN: cpu unknown - Performance data not found!
[root@mon01 libexec]# ./check_rhev3.pl -H XXXXXX  -a nagios@internal:XXXXXXXX   -R hyp-app-03 -l  load
RHEV UNKNOWN: cpu.load.avg.5m unknown - Performance data not found!
 
 
 
I have replaced the RHEVM hostname and password with XXXX

**Comment by scrat14** [comment]
Hi,

can you please send me some debug output? Please run the script with -vvv option and post it here or send it to me via email (rkoch@rk-it.at) if you don't want to have the debug information published in public.
E.g.: [root@mon01 libexec]# ./check_rhev3.pl -H XXXXXX -a nagios@internal:XXXXXX -R hyp-app-03 -l memory -vvv
Thanks!

**Comment by rishisingh1210** [comment]
Hi,



please find below

[root@mon01 libexec]# ./check_rhev3.pl -H rhevm01.qdc.aras.com -a nagios@internal:XXXXXXXXX -R hyp-app-03.qdc.aras.com -l  load
RHEV UNKNOWN: cpu.load.avg.5m unknown - Performance data not found!


[root@mon01 libexec]# ./check_rhev3.pl -H rhevm01.qdc.aras.com -a nagios@internal:XXXXXXX -R hyp-app-03.qdc.aras.com -l  load -vvv
[V] Starting the main script.
[V] This is check_rhev3 version 1.4.0.
[V] Checking which component to monitor.
[D] check_host: Called function check_host.
[V] Host: Checking host hyp-app-03.qdc.aras.com.
[D] check_statistics: Called function check_statistics.
[V] Statistics: Checking statistics of hosts.
[D] check_statistics: Input parameter $component: hosts
[D] check_statistics: Input parameter $search: hyp-app-03.qdc.aras.com
[D] check_statistics: Input parameter $statistics: cpu.load.avg.5m
[D] check_statistics: Converting variables.
[D] check_statistics: Converted variable $url: hosts
[D] get_result: Called function get_result.
[D] get_result: Input parameter $_[0]: /hosts?search=name%3Dhyp-app-03.qdc.aras.com
[D] get_result: Input parameter $xml: hosts
[D] get_result: Input parameter $search: id
[D] rhev_connect: Called function rhev_connect.
[V] REST-API: Connecting to REST-API.
[D] rhev_connect: Input parameter: /hosts?search=name%3Dhyp-app-03.qdc.aras.com.
[V] REST-API: RHEVM-API URL: https://rhevm01.qdc.aras.com:443/api/hosts?search=name%3Dhyp-app-03.qdc.aras.com
[V] REST-API: RHEVM-API User: nagios@internal
[V] REST-API: cookie filename: cmhldm0wMS5xZGMuYXJhcy5jb20tbmFnaW9zQGludGVybmFsCg==
[D] rhev_connect: Trying cookie authentication.
[D] rhev_connect: Using cookie: JSESSIONID=59JUiivc6f-FedfDgT5vfhUI
[V] REST-API: Cache-Control: no-cache
Connection: close
Date: Thu, 19 May 2016 06:37:43 GMT
Pragma: No-cache
Vary: Accept-Encoding
Content-Length: 65
Content-Type: application/xml
Expires: Thu, 01 Jan 1970 00:00:00 UTC
Client-Date: Thu, 19 May 2016 06:37:43 GMT
Client-Peer: 10.253.100.182:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/O=qdc.aras.com/CN=rhevm01.qdc.aras.com.35878
Client-SSL-Cert-Subject: /C=US/O=qdc.aras.com/CN=rhevm01.qdc.aras.com
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Warning: Peer certificate not verified
JSESSIONID: 59JUiivc6f-FedfDgT5vfhUI
[D] rhev_connect: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hosts/>
[D] get_result: %result: [D] get_result: Looping through %result.
[D] check_statistics: %id: [D] check_statistics: Looping through %id.
[V] Statistics: warning value: 60.
[V] Statistics: critical value: 80.
RHEV UNKNOWN: cpu.load.avg.5m unknown - Performance data not found!
[root@mon01 libexec]#





Rishikesh Singh
Specialist/Engineer, GEO Services Operations MEIA
SITA
E-Mail:        Rishikesh.singh@sita.aero
Direct:         +974-33722808
CVS:                3012870
Mobile:        +974-77271014
Address:  SITA|Hamad International Airport  | DOHA|Qatar

Join the conversation:
[cid:image003.jpg@01D1B1B2.68471900]<http://www.sita.aero/resources/sita-social>
www.sita.aero
Please consider your environmental responsibility before printing

**Comment by scrat14** [comment]
RHEVM-API doesn't send any information about your host:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hosts/>

It seems that RHEVM-API can't find your host (if this is the case an empty hosts XML-element is returned). A successful search for a host looks like this:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hosts>
    <host href="/api/hosts/92ed88a6-faeb-4e7c-8037-1cf49a4961fb" id="92ed88a6-faeb-4e7c-8037-1cf49a4961fb">
...

Can you please check if the hostname you specified for -R option is the same as in column "Name" in RHEVM hosts tab?

**Comment by scrat14** [comment]
Is this still an issue or did you manage to fix it already?

**Comment by rishisingh1210** [comment]
We fixed it !   we used the same name as displayed in RHVEM ui (case sensitive )


Rishikesh Singh
Specialist/Engineer, GEO Services Operations MEIA
SITA
E-Mail:       Rishikesh.singh@sita.aero
Direct:        +974-33722808
CVS:              3012870
Mobile:       +974-77271014
Address:  SITA|Hamad International Airport  | DOHA|Qatar

Join the conversation:
[cid:image002.jpg@01D1BCCF.095FF1F0]<http://www.sita.aero/resources/sita-social>
www.sita.aero
Please consider your environmental responsibility before printing
