### ISSUE TITLE
Critical/Warning thresholds for -l vms/hosts are ignored

### ISSUE THREAD

**Issue by Jerazol** [ovido/check_rhev3#44]
The check against $tmp_state on line [1630](https://github.com/ovido/check_rhev3/blob/master/plugin-dir/check_rhev3.pl#L1630) and [1633](https://github.com/ovido/check_rhev3/blob/master/plugin-dir/check_rhev3.pl#L1633) means that any thresholds specified will be ignored. 

Example:
/usr/local/bin/check_rhev3.pl -H rhevm.somesite.net -f /etc/nagios/rhevm_credentials -C mycluster -l vms -w 50 -c 20
RHEV CRITICAL: Vms critical - 62/66 Vms with state UP |Vms_up=62;50;20;0; restoring_state=0;;;0; image_illegal=0;;;0; powering_down=0;;;0; reboot_in_progress=0;;;0; image_locked=0;;;0; unassigned=0;;;0; unknown=0;;;0; down=4;;;0; wait_for_launch=0;;;0; not_responding=0;;;0; powering_up=0;;;0; saving_state=0;;;0; migrating_to=0;;;0; paused=0;;;0; migrating_from=0;;;0; suspended=0;;;0;

**Comment by scrat14** [comment]
Thanks for reporting this bug. Let me verify it and provide a fix for it.

**Comment by Jerazol** [comment]
I simply removed the reference to $tmp_state in the checks. From what I can tell, it looks like $tmp_state implements a hard check without thresholds. Given the check against warning and critical thresholds $tmp_state seems redundant?

**Comment by scrat14** [comment]
@Jerazol: can you please check latest commit if this works in your environment? Thanks.

**Comment by Jerazol** [comment]
Thanks, I have tested it with the same command that failed previously and am unable to reproduce the error.
