### ISSUE TITLE
element has non-​unique value in 'id' key attribute

### ISSUE THREAD

**Issue by lbischof** [ovido/check_rhev3#45]
I would like to check the storage:

```
./check_rhev3.pl -D datacenter -H manager.domain.com -a user@ldap:password -l storage -s usage
```

But the following warning appears multiple times above the results:

```
Warning: <logical_​unit> element has non-​unique value in 'id' key attribute: 2...31 at /usr/lib64/nagios/plugins/custom/check_​rhev3.​pl line 1715
```

There are duplicate key addributes. What am I doing wrong?

**Comment by lbischof** [comment]
I opened a ticket at redhat and this was their response:

From the analysis we found below information :
Attribute 20000000004680da6 is your lun and has 3 connections due to multipath. This lun is associated with storage domain: data06
This is an expected behavior and do not see any issue from RHEV side.

It would be great if the warning didn't appear in the output though.

**Comment by scrat14** [comment]
Can you please send me full debug output (start script with -vvv) so I can check what's going on?
Btw, please give me a few days for next response as I'm on vacation right now.

Thanks,
René

**Comment by lbischof** [comment]
No problem. I just assumed that the error came from rhev. I sent you the output via Email, because I'm not sure if it contains any private infos. Thanks for looking into this!

**Comment by lbischof** [comment]
Based on our email conversation the warning appears to come from perl checking if the xml output is valid. @scrat14  kindly offered to ask the ovirt developers about the invalid xml. 

Did you get around to asking the oVirt developers? If they don't think it necessary to have valid xml, then maybe you could add an option to the plugin so that I can ignore the warning? Currently it's very confusing when there is an Icinga warning and users see the xml warning...

**Comment by scrat14** [comment]
Sorry, I didn't had any time to investigate this further / discuss with oVirt guys.

**Comment by scrat14** [comment]
merged pull request - will be added to check_rhev3 1.6
