### ISSUE TITLE
perl dependency when installing

### ISSUE THREAD

**Issue by almumontiel** [ovido/check_rhev3#46]
Hello
I have tried to install the rpm on my system.
[root@nagios ~]# uname -a
Linux nagios.ft.uam.es 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 15:13:20 CDT 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@nagios ~]# cat /etc/redhat-release 
Scientific Linux release 6.8 (Carbon)
I have perl installed:
[root@nagios ~]# perl -v

This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi
...

And the modules:
[root@nagios ~]# instmodsh
Available commands are:
   l            - List all installed modules
   m <module>   - Select a module
   q            - Quit the program
cmd? l
Installed modules are:
   Encode::Locale
   Getopt::Long
   HTTP::Cookies
   HTTP::Date
   HTTP::Negotiate
   IO::HTML
   LWP::MediaTypes
   Perl
   Test::Simple
   WWW::RobotRules
   XML::NamespaceSupport
   XML::SAX
   XML::SAX::Base
   XML::SAX::Expat
   XML::Simple
cmd? q

I get this error message while installing the rpm:
[root@nagios check_rhev3-1.5]# yum install /root/rpmbuild/RPMS/x86_64/nagios-plugins-rhev3-1.5-1.el6.x86_64.rpm 
Loaded plugins: priorities, security, versionlock
Setting up Install Process
Examining /root/rpmbuild/RPMS/x86_64/nagios-plugins-rhev3-1.5-1.el6.x86_64.rpm: nagios-plugins-rhev3-1.5-1.el6.x86_64
Marking /root/rpmbuild/RPMS/x86_64/nagios-plugins-rhev3-1.5-1.el6.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package nagios-plugins-rhev3.x86_64 0:1.5-1.el6 will be installed
--> Processing Dependency: /bin/perl for package: nagios-plugins-rhev3-1.5-1.el6.x86_64
--> Processing Dependency: /bin/perl for package: nagios-plugins-rhev3-1.5-1.el6.x86_64
--> Finished Dependency Resolution
--> Finding unneeded leftover dependencies
Found and removing 0 unneeded dependencies
Error: Package: nagios-plugins-rhev3-1.5-1.el6.x86_64 (/nagios-plugins-rhev3-1.5-1.el6.x86_64)
           Requires: /bin/perl
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

I appreciate any help.Thanks and regards,
almudena

**Comment by scrat14** [comment]
Thanks for reporting this issue. Same happens on CentOS 6 (no problems on CentOS 7).
I'll create a new package for CentOS/SL 6 and will upload it in the next days.

**Comment by scrat14** [comment]
Package for CentOS/SL/RHEL 6 is uploaded: https://github.com/ovido/check_rhev3/releases/download/check_rhev3-1.5/nagios-plugins-rhev3-1.5-2.1-el6.x86_64.rpm
