### ISSUE TITLE
Data truncated

### ISSUE THREAD

**Issue by Caez83** [ovido/check_rhev3#47]
Hello,

I have a probleme with the check on ovirt 3.6
I have 2 clusters.
One is OK, but in the second, the data is truncated on the XML:

The options:
-H host -a login@domain:pass -l hosts -C cl1  -o 
(I have the same problem with the network )

```
        <summary>
            <active>12</active>
            <migrating>0</migrating>
            <total>12</total>
        </summary>
        <protocol>stomp</protocol>
        <os type="oVirt Node">
            <version full_version="3.6 - 0.999.201606071021.el7.centos"RHEV CRITICAL: Error in XML returned from RHEVM - enable debug mode for details.
Can't use an undefined value as a HASH reference at test.pl line 700.
```

Have you got an idea for this issue ?
I don't know if the issue is on the script or in ovirt limitation.

Best regards

**Comment by scrat14** [comment]
Can you please attach the full debug output (add -vvv to your plugin call)?
If it contains sensitive data or you don't want to add it to public bug tracking please send it to me via email: rkoch@rk-it.at.
Thanks.

**Comment by niksverige** [comment]
i´m having the same issue. Here is output with -vvv

[V] Starting the main script.
[V] This is check_rhev3 version 1.5.0.
[V] Checking which component to monitor.
[D] check_host: Called function check_host.
[V] Host: Checking host gotprhev5.
[V] Host: No check is specified, checking host status.
[D] check_cstatus: Called function check_cstatus.
[D] check_status: Called function check_status.
[V] Status: Checking status of hosts.
[D] check_status: Input parameter $components: hosts
[D] check_status: Input parameter $search: gotprhev5
[D] check_status: Converting variables.
[D] check_status: Converted variable $components: hosts
[D] check_status: Converted variable $component: host
[D] rhev_connect: Called function rhev_connect.
[V] REST-API: Connecting to REST-API.
[D] rhev_connect: Input parameter: /hosts?search=name%3Dgotprhev5.
[V] REST-API: RHEVM-API URL: https://rhevm:443/ovirt-engine/api/hosts?search=name%3Dgotprhev5
[V] REST-API: RHEVM-API User: admin@internal
[V] REST-API: cookie filename: cmhldm0tYWRtaW5AaW50ZXJuYWwK
[D] rhev_connect: Trying cookie authentication.
[D] rhev_connect: Using cookie: JSESSIONID=xmnpQIN75p6wLgo4O3pfevQdw31Fhe3LY_i0gHbf.rhevm
[V] REST-API: Connection: close
Date: Fri, 18 Nov 2016 12:00:06 GMT
Server: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.1e-fips
Vary: Accept-Encoding
Content-Length: 7093
Content-Type: application/xml
Client-Date: Fri, 18 Nov 2016 12:00:09 GMT
Client-Peer: 10.67.10.58:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/O=got.DOMAIN.com/CN=rhevm.got.DOMAIN.com.50440
Client-SSL-Cert-Subject: /C=US/O=got.DOMAIN.com/CN=rhevm.got.DOMAIN.com
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Warning: Peer certificate not verified
[D] rhev_connect: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hosts>
    <host href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0" id="7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0">
 <actions>
            <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/upgrade" rel="upgrade"/>
            <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/enrollcertificate" rel="enrollcertificate"/>
            <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/iscsidiscover" rel="iscsidiscover"/>
            <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/forceselectspm" rel="forceselectspm"/>
            <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/approve" rel="approve"/>
            <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/commitnetconfig" rel="commitnetconfig"/>
            <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/iscsilogin" rel="iscsilogin"/>
            <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/unregisteredstoragedomainsdiscover" rel="unregisteredstoragedomainsdiscover"/>
            <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/deactivate" rel="deactivate"/>
            <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/refresh" rel="refresh"/>
            <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/setupnetworks" rel="setupnetworks"/>
            <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/fence" rel="fence"/>
            <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/install" rel="install"/>
            <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/activate" rel="activate"/>
        </actions>
        <name>gotprhev5</name>
        <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/affinitylabels" rel="affinitylabels"/>
        <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/devices" rel="devices"/>
        <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/fenceagents" rel="fenceagents"/>
        <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/hooks" rel="hooks"/>
        <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/katelloerrata" rel="katelloerrata"/>
        <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/networkattachments" rel="networkattachments"/>
        <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/nics" rel="nics"/>
        <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/numanodes" rel="numanodes"/>
        <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/permissions" rel="permissions"/>
        <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/statistics" rel="statistics"/>
        <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/storage" rel="storage"/>
        <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/storageconnectionextensions" rel="storageconnectionextensions"/>
        <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/tags" rel="tags"/>
        <link href="/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/unmanagednetworks" rel="unmanagednetworks"/>
        <address>10.67.7.234</address>
        <auto_numa_status>enable</auto_numa_status>
        <certificate>
            <organization>got.DOMAIN.com</organization>
            <subject>O=got.DOMAIN.com,CN=10.67.7.234</subject>
        </certificate>
        <cpu>
 <name>Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz</name>
            <speed>2411</speed>
            <topology>
                <cores>12</cores>
                <sockets>2</sockets>
                <threads>2</threads>
            </topology>
        </cpu>
        <device_passthrough>
            <enabled>false</enabled>
        </device_passthrough>
        <external_status>ok</external_status>
        <hardware_information>
            <manufacturer>Dell Inc.</manufacturer>
            <product_name>PowerEdge R630</product_name>
            <serial_number>5CR0H92</serial_number>
            <supported_rng_sources>
                <supported_rng_source>random</supported_rng_source>
            </supported_rng_sources>
            <uuid>4C4C4544-0043-5210-8030-B5C04F483932</uuid>
        </hardware_information>
        <iscsi>
            <initiator>iqn.1994-05.com.redhat:2e70472aa45f</initiator>
        </iscsi>
        <kdump_status>disabled</kdump_status>
        <ksm>
            <enabled>false</enabled>
        </ksm>
        <libvirt_version>
            <build>0</build>
            <full_version>libvirt-2.0.0-10.el7</full_version>
            <major>2</major>
            <minor>0</minor>
            <revision>0</revision>
        </libvirt_version>
        <max_scheduling_memory>31434211328</max_scheduling_memory>
        <memory>270193917952</memory>
        <numa_supported>true</numa_supported>
        <os>
 <custom_kernel_cmdline></custom_kernel_cmdline>
            <reported_kernel_cmdline>BOOT_IMAGE=/vmlinuz-3.10.0-514.el7.x86_64 root=/dev/mapper/rhel-root ro crashkernel=auto rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet LANG=en_US.UTF-8</reported_kernel_cmdline>
            <type>RHEL</type>
            <version>
                <full_version>7.3 - 7.el7</full_version>
                <major>7</major>
                <minor>3</minor>
            </version>
        </os>
        <port>54321</port>
        <power_management>
            <automatic_pm_enabled>true</automatic_pm_enabled>
            <enabled>false</enabled>
            <kdump_detection>true</kdump_detection>
            <pm_proxies/>
        </power_management>
        <protocol>stomp</protocol>
        <se_linux>
            <mode>disabled</mode>
        </se_linux>
        <spm>
            <priority>5</priority>
            <status>none</status>
        </spm>
        <ssh>
            <fingerprint>SHA256:7ETGsPbWqUdv+jAipnDYOp1+6Gc/vgDWPisgTC09OYY</fingerprint>
            <port>22</port>
        </ssh>
        <status>up</status>
        <summary>
            <active>25</active>
            <migrating>0</migrating>
            <total>25</total>
        </summary>
        <transparent_hugepages>
            <enabled>true</enabled>
        </transparent_hugepages>
        <type>rhel</type>
 <update_available>true</update_available>
        <version>
            <build>13</build>
            <full_version>vdsm-4.18.13-1.el7ev</full_version>
            <major>4</major>
            <minor>18</minor>
            <revision>0</revision>
        </version>
        <cluster href="/ovirt-engine/api/clusters/d49ef21f-29ac-4e3a-bcf4-4185f2338928" id="d49ef21f-29ac-4e3a-bcf4-4185f2338928"/>
    </host>
</hosts>
[D] check_status: %result: $VAR1 = 'host';
$VAR2 = {
          'protocol' => 'stomp',
          'device_passthrough' => {
                                  'enabled' => 'false'
                                },
          'auto_numa_status' => 'enable',
          'ssh' => {
                   'fingerprint' => 'SHA256:7ETGsPbWqUdv+jAipnDYOp1+6Gc/vgDWPisgTC09OYY',
                   'port' => '22'
                 },
          'os' => {
                  'custom_kernel_cmdline' => {},
                  'version' => {
                               'full_version' => '7.3 - 7.el7',
                               'minor' => '3',
                               'major' => '7'
                             },
                  'type' => 'RHEL',
                  'reported_kernel_cmdline' => 'BOOT_IMAGE=/vmlinuz-3.10.0-514.el7.x86_64 root=/dev/mapper/rhel-root ro crashkernel=auto rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet LANG=en_US.UTF-8'
                },
          'libvirt_version' => {
                               'revision' => '0',
                               'full_version' => 'libvirt-2.0.0-10.el7',
                               'minor' => '0',
                               'major' => '2',
                               'build' => '0'
                             },
          'ksm' => {
  'enabled' => 'false'
                 },
          'hardware_information' => {
                                    'serial_number' => '5CR0H92',
                                    'manufacturer' => 'Dell Inc.',
                                    'uuid' => '4C4C4544-0043-5210-8030-B5C04F483932',
                                    'supported_rng_sources' => {
                                                               'supported_rng_source' => 'random'
                                                             },
                                    'product_name' => 'PowerEdge R630'
                                  },
          'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0',
          'id' => '7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0',
          'address' => '10.67.7.234',
          'iscsi' => {
                     'initiator' => 'iqn.1994-05.com.redhat:2e70472aa45f'
                   },
          'transparent_hugepages' => {
                                     'enabled' => 'true'
                                   },
          'cpu' => {
                   'topology' => {
                                 'sockets' => '2',
                                 'threads' => '2',
                                 'cores' => '12'
                               },
                   'speed' => '2411',
                   'name' => 'Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz'
                 },
          'numa_supported' => 'true',
          'name' => 'gotprhev5',
          'spm' => {
                   'priority' => '5',
                   'status' => 'none'
                 },
          'port' => '54321',
          'memory' => '270193917952',
          'max_scheduling_memory' => '31434211328',
          'update_available' => 'true',
          'type' => 'rhel',
          'actions' => {
                       'link' => [
                                 {
                                   'rel' => 'upgrade',
                                   'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/upgrade'
                                 },
                                 {
                                   'rel' => 'enrollcertificate',
                                   'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/enrollcertificate'
                                 },
                                 {
                                   'rel' => 'iscsidiscover',
                                   'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/iscsidiscover'
                                 },
                                 {
                                   'rel' => 'forceselectspm',
                                   'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/forceselectspm'
                                 },
                                 {
                                   'rel' => 'approve',
                                   'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/approve'
                                 },
                                 {
                                   'rel' => 'commitnetconfig',
                                   'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/commitnetconfig'
                                 },
                                 {
                                   'rel' => 'iscsilogin',
                                   'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/iscsilogin'
                                 },
                                 {
                                   'rel' => 'unregisteredstoragedomainsdiscover',
                                   'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/unregisteredstoragedomainsdiscover'
                                 },
                                 {
                                   'rel' => 'deactivate',
                                   'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/deactivate'
                                 },
                                 {
                                   'rel' => 'refresh',
                                   'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/refresh'
                                 },
                                 {
                                   'rel' => 'setupnetworks',
                                   'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/setupnetworks'
                                 },
                                 {
                                   'rel' => 'fence',
                                   'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/fence'
                                 },
                                 {
                                   'rel' => 'install',
                                   'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/install'
                                 },
                                 {
                                   'rel' => 'activate',
                                   'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/activate'
                                 }
                               ]
                     },
          'certificate' => {
                           'subject' => 'O=got.DOMAIN.com,CN=10.67.7.234',
                           'organization' => 'got.DOMAIN.com'
                         },
          'power_management' => {
                                'automatic_pm_enabled' => 'true',
                                'pm_proxies' => {},
                                'kdump_detection' => 'true',
                                'enabled' => 'false'
                              },
          'status' => 'up',
          'summary' => {
                       'migrating' => '0',
                       'active' => '25',
                       'total' => '25'
                     },
          'se_linux' => {
                        'mode' => 'disabled'
                      },
          'link' => [
                    {
                      'rel' => 'affinitylabels',
                      'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/affinitylabels'
                    },
                    {
                      'rel' => 'devices',
                      'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/devices'
                    },
                    {
                      'rel' => 'fenceagents',
                      'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/fenceagents'
                    },
                    {
                      'rel' => 'hooks',
                      'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/hooks'
                    },
                    {
                      'rel' => 'katelloerrata',
                      'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/katelloerrata'
                    },
                    {
                      'rel' => 'networkattachments',
                      'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/networkattachments'
                    },
                    {
                      'rel' => 'nics',
                      'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/nics'
                    },
                    {
                      'rel' => 'numanodes',
                      'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/numanodes'
                    },
                    {
                      'rel' => 'permissions',
                      'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/permissions'
                    },
                    {
                      'rel' => 'statistics',
                      'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/statistics'
                    },
                    {
                      'rel' => 'storage',
                      'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/storage'
                    },
                    {
                      'rel' => 'storageconnectionextensions',
                      'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/storageconnectionextensions'
                    },
                    {
                      'rel' => 'tags',
                      'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/tags'
                    },
                    {
                      'rel' => 'unmanagednetworks',
                      'href' => '/ovirt-engine/api/hosts/7e5bc8e9-8034-4fc6-b15a-c6b9b2abcec0/unmanagednetworks'
                    }
                  ],
          'cluster' => {
                       'href' => '/ovirt-engine/api/clusters/d49ef21f-29ac-4e3a-bcf4-4185f2338928',
                       'id' => 'd49ef21f-29ac-4e3a-bcf4-4185f2338928'
                     },
          'version' => {
                       'revision' => '0',
                       'full_version' => 'vdsm-4.18.13-1.el7ev',
                       'minor' => '18',
                       'major' => '4',
                       'build' => '13'
                     },
          'external_status' => 'ok',
          'kdump_status' => 'disabled'
        };
[D] check_status: Looping through %result
[V] Status: single hash entry found.
[D] check_status: Converting variable $components.
[D] check_status: Converted variable $components: host
Can't use string ("up") as a HASH ref while "strict refs" in use at ./check_rhev3 line 753.

**Comment by scrat14** [comment]
Can you please send me the output via mail as it's not really readable here: rkoch@rk-it.at. Thanks.
Does it occur with check_rhev3 1.6, too?

**Comment by niksverige** [comment]
Email sent. I using this on rhev4
thanks
/Nik

**Comment by scrat14** [comment]
The issue was following:
check_rhev3 1.6 is required for RHEV 4 and api option must be set to -A /ovirt-engine/api
