### ISSUE TITLE
check_rhev3.pl will not work with oVirt 4 (wrong API endpoint)

### ISSUE THREAD

**Issue by mykaul** [ovido/check_rhev3#48]
The endpoint has moved to <rhev>/ovirt-engine/api , but it is still referred to /api in the code.
This may work in 3.6, but will fail on 4.0.

**Comment by scrat14** [comment]
The new api will work in check_rhev3 from master, as patch #42 was merged.
Sadly I didn't had enough time to release a new version, yet, but will try to get a new release out this week.

**Comment by scrat14** [comment]
fixed in version 1.6 - added information to release notes for changing api path.
version 1.6 will still have the old path (/api) as a default value to avoid breaking older installations - will be changed in later releases...
