### ISSUE TITLE
When using '*' and option '-l usage', output is incomplete

### ISSUE THREAD

**Issue by nlameiras** [ovido/check_rhev3#51]
When checking storage domains with "*" option and "-l usage" option, output is not correct. Only the last volume output is written to STDOUT. I was expecting information concerning all volumes.
exemple  (I currently have 15 volumes in ovirt-engine) : 
<pre>
$ ./check_rhev3 -H ovirt-engine -A /ovirt-engine/api -a username:password -S \* -l usage
RHEV OK: storage ok - 29.17% used (Export) |storage_Export=29.17%;60;80;0;
</pre>

"Export" is the last storage, 14 other storages are missing from the output.

When using the "-vvv" option, we clearly see that all volumes are analysed, but only the last one is "outputed", so maybe it is a "concatenation" bug ?

FYI : I have seen this problem with other options using '*', but have not memorised them all.

**Comment by nlameiras** [comment]
I was able to find a quick fix by un-commenting line 973 and commenting line 974 of file check_rhev3 (version 1.6). I'm not sure this won't have a negative impact on other "options" so I did not dare to propose a patch since I do not fully understand the consequences of my proposed change. Maybe the author can bring us some information? thanks for awesome plugin anyway!

**Comment by scrat14** [comment]
Thanks a lot for reporting this bug. It was reported by other users as well, but I didn't had enough time to debug it further, yet. I'll have a look at the lines mentioned by you and will let you know.
Please give me a few days.

**Comment by scrat14** [comment]
Sorry for late response. Un-commenting line 973 will indead fix this issue, but the datacenter usage check (-D datacenter -l storage -s usage) will fail afterwards. I'll rewrite one of these 2 checks to make sure both use the same logic and do not exclude each other...

**Comment by scrat14** [comment]
nlameiras, 
can you please test latest version from master branch, which should fix this issue? Thanks

**Comment by nlameiras** [comment]
hello,

just tested latest version, and is OK.

great work, tnx
