### ISSUE TITLE
Check RHEV Host VMs (-l vms) fails with RHEV UNKNOWN: Host ' ' not found when no vms on host

### ISSUE THREAD

**Issue by dongursli** [ovido/check_rhev3#53]
Have been running this script in Nagios for a while and suddenly it failed.
Running is from the CLI
check_rhev3.pl -H rhevm -p 443 -f .rhevauth -R RHEVHOST -l vms
RHEV UNKNOWN: Host RHEVHOST not found.

Saw that here is no vm running on the RHEVHOST. If I start a VM on the RHEVHOST the "RHEV UNKNOWN" goes away.

I think this is a bug. 

Have provided a -vvv output.
check_rhev3.pl -vvv -H rhevm -p 443 -f .rhevauth -R RHEVHOST -l vms
[V] Starting the main script.
[V] This is check_rhev3 version 1.6.0.
[V] Checking which component to monitor.
[D] check_host: Called function check_host.
[V] Host: Checking host RHEVHOST.
[D] check_cstatus: Called function check_cstatus.
[D] check_status: Called function check_status.
[V] Status: Checking status of hostvms.
[D] check_status: Input parameter $components: hostvms
[D] check_status: Input parameter $search: RHEVHOST
[D] check_status: Converting variables.
[D] check_status: Converted variable $components: hostvms
[D] check_status: Converted variable $component: hostvm
[D] rhev_connect: Called function rhev_connect.
[V] REST-API: Connecting to REST-API.
[D] rhev_connect: Input parameter: /vms?search=host%3DRHEVHOST.
[V] REST-API: RHEVM-API URL: https://rhevm.:443/api/vms?search=host%3DRHEVHOST
[V] REST-API: RHEVM-API User: 
[V] REST-API: cookie filename: 
[D] rhev_connect: Trying cookie authentication.
[D] rhev_connect: Using cookie: JSESSIONID=
[V] REST-API: Cookie authentication failed - using username and password.
[D] rest_api_connect: Called function rest_api_connect.
[V] REST-API: Connecting to REST-API.
[D] rest_api_connect: Input parameter: HTTP::Request=HASH(0x1684af0).
[D] rest_api_connect: Input parameter: LWP::UserAgent=HASH(0x1677db8).
[D] rest_api_connect: Input parameter: 
[V] REST-API: Cache-Control: no-cache
Connection: close
Date: Tue, 28 Mar 2017 12:03:02 GMT
Pragma: No-cache
Vary: Accept-Encoding
Content-Length: 63
Content-Type: application/xml
Expires: Thu, 01 Jan 1970 01:00:00 CET
Client-Date: Tue, 28 Mar 2017 12:03:02 GMT
Client-Peer: xxx.xxx.xxx.xxx:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: CN=Certificate Authority
Client-SSL-Cert-Subject: CN=rhevm
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Warning: Peer certificate not verified
JSESSIONID: 
[D] rest_api_connect: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<vms/>
[V] REST-API: Cache-Control: no-cache
Connection: close
Date: Tue, 28 Mar 2017 12:03:02 GMT
Pragma: No-cache
Vary: Accept-Encoding
Content-Length: 63
Content-Type: application/xml
Expires: Thu, 01 Jan 1970 01:00:00 CET
Client-Date: Tue, 28 Mar 2017 12:03:02 GMT
Client-Peer: xxx.xxx.xxx.xxx:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: CN=Certificate Authority
Client-SSL-Cert-Subject: CN=rhevm
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Warning: Peer certificate not verified
JSESSIONID: 
[D] rhev_connect: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<vms/>
[D] check_status: %result: [D] check_status: Looping through %result
[V] Status: Search pattern RHEVHOST not found.
[D] print_notfound: Called function print_notfound.
[D] print_notfound: Input parameter: Host
[D] print_notfound: Input parameter: RHEVHOST
RHEV UNKNOWN: Host RHEVHOST not found.

**Comment by scrat14** [comment]
Thanks for reporting this bug.
I can verify it with oVirt 4.1 and latest version of check_rhev3 (from master branch). The output is a bit different but still not correct:

```
$ ./check_rhev3.pl -f /tmp/auth -H engine -A /ovirt-engine/api -R node01 -l vms
RHEV UNKNOWN: Host node01 not found.
```

I'll fix this in next version.

**Comment by scrat14** [comment]
This issue is fixed in new repository: https://github.com/rk-it-at/check_rhv/commit/414fa26b0495700c9d12e8a86c2d16a03cc36f69
