### ISSUE TITLE
(new) api user not working

### ISSUE THREAD

**Issue by Klar** [ovido/check_rhev3#56]
Hi,

First, thanks for the script!

I have Ovirt-Engine 4.1 and the script is working with the default admin@internal user. I want to create a new user (best read only) only for API but I don't get it to work. I tried with new Admin User and treid to add it to the viewer group, which I could not find.

I also couldn't find a proper Ovirt API Docu. 

Thanks for your / someone's help.

**Comment by scrat14** [comment]
Here are some instructions on how to add a new user in RHV 4.1 (same for oVirt 4.1).

In this example I create a new user for the internal domain - if you use a directory server like IPA or AD you can skip this step and add system permissions directly.
```

root@engine:~# ovirt-aaa-jdbc-tool user add monitoring --attribute=firstName=Monitoring --attribute=lastName=User
adding user monitoring...
user added successfully
Note: by default created user cannot log in. see:
/usr/bin/ovirt-aaa-jdbc-tool user password-reset --help
```

Set password for this user.

```
root@engine:~# /usr/bin/ovirt-aaa-jdbc-tool user password-reset monitoring --password-valid-to="2025-08-01 12:00:00-0800"
Password:
Reenter password:
updating user monitoring...
user updated successfully
```

Give user role "Read-Only-Admin" to this user in RHV Administration Portal.

Go to **Configure** - **System Permissions** - **Add** and add your user wiith role **ReadOnlyAdmin**.

Now you can monitor your environment - here are 2 examples for datacenter and vm monitoring with this user:

```
[icinga@monitoring plugin-dir]$ ./check_rhev3.pl -H engine.lab.rk-it.at -a monitoring@internal:xxxx -A "/ovirt-engine/api" -D Default 
RHEV OK: Datacenters ok - 1/1 Datacenters with state UP ,0 Datacenters in non-critical state|Datacenters_up=1;1;1;0; uninitialized=0;;;0; not_operational=0;;;0; problematic=0;;;0; contend=0;;;0; maintenance=0;;;0; non_critical=0;;;0; 

[icinga@monitoring plugin-dir]$ ./check_rhev3.pl -H engine.lab.rk-it.at -a monitoring@internal:icinga -A "/ovirt-engine/api" -M rhws01 -l cpu -s usage
RHEV OK: cpu ok - 0.15% used (rhws01) |cpu=0.15%;60;80;0; cpu.current.guest=0.15;;;0; cpu.current.hypervisor=0;;;0; 
```

**Comment by Klar** [comment]
thank you it worked
