### ISSUE TITLE
check for "update available"

### ISSUE THREAD

**Issue by Klar** [ovido/check_rhev3#57]
Hi,

Thanks for the Script, it's working fine and it is as expected. One thing what I am missing is that there is no check for the hosts if an update is available.

Did a little search and found this:

https://ovirt.github.io/ovirt-engine-api-model/master/#services/host
`POST /hosts/{host:id}/upgradecheck`

I think that can be implemented, but not sure how. I just need a Warning if an Update is available on one of my hosts. 

Would be nice if someone has the time to do this.

much appreciated

**Comment by scrat14** [comment]
I think this make sense to implement. I'll add it to the roadmap...

**Comment by scrat14** [comment]
This feature is implemented in new repository: https://github.com/rk-it-at/check_rhv/commit/861e2c4c0be2869633624f328c8b282d62e25548
