### ISSUE TITLE
--cookie option is ignored

### ISSUE THREAD

**Issue by wferi** [ovido/check_rhev3#60]
If one wants to avoid interference between different Unix users using the plugin with the same API user, it's better to avoid writing temporary files and keep the check plugin stateless. The `--cookie` option sounds like a possible solution, but it does not have any effect. Please provide a way to avoid writing the cookie file (I don't mind losing the NIC error reports with it).

**Comment by scrat14** [comment]
Thanks for opening this request.
As this plugin is a monitoring plugin for Nagios and Icinga (and other Nagios-based solutions), I don't see a need for this. If a user wants to test the plugin manually, just use sudo (-u nagios|icinga) to avoid issues.
